### ISSUE TITLE
[News detail] Insert emoji không đúng vị trí ô comment

### ISSUE THREAD

**Issue by vanquang9387** [rikkeisoft/make-rikkeisoft-news-great-again#1]
### Steps to reproduce
- Vào chi tiết bài viết
- Nhấn "Phản hồi" ở 1 comment đã có
- Nhấn emoji button, chọn 1 emoji
=> Emoji được insert ở ô root comment, không phải ở ô phản hồi
![GifMaker_20190613094937845](https://user-images.githubusercontent.com/7125810/59400143-a734bf80-8dc0-11e9-96ef-6fa4ec3e3f0e.gif)

Có vẻ mutationObserverCallback được chạy sau khi đã nhấn vào 1 emoji button nên chưa kịp update RKVN.LAST_FOCUSED_EDITOR

**Comment by hnq90** [comment]
Cảm ơn anh Quang đã report nhé 👍 Keep going 💯

**Comment by hnq90** [comment]
Fixed: https://github.com/rikkeisoft/make-rikkeisoft-news-great-again/commit/83f48576c1fe8e6b576f28cfdf8d12f51b4f5fa9
